name: deploy
on: [push]

jobs:
  production:
    runs-on: ubuntu-latest
    name: production
    steps:
      - name: Get Pokemon name
        uses: ibrahimejaz/actiontesting@main
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
    
  staging:
    runs-on: ubuntu-latest
    name: staging
    steps:
      - name: Get Pokemon name
        uses: ibrahimejaz/actiontesting@main
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
